id: P000674
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20813
  title: སྦྲང་ཆར། ༼དུས་དེབ།༽
  author: ''
  volumes:
    ae5122cebbb84790a638bb22105ffd17:
      image_group_id: I1KG14436
      title: ''
      volume_number: 112
      total_pages: 218
    ef228c721c964c5ba3f395148f51678e:
      image_group_id: I1KG14437
      title: ''
      volume_number: 113
      total_pages: 218
    bf928d5b772941269ae25adaa4c73420:
      image_group_id: I1KG14438
      title: ''
      volume_number: 114
      total_pages: 218
    5007520922c54abca60a1c43d5146061:
      image_group_id: I1KG14439
      title: ''
      volume_number: 115
      total_pages: 218
    ce6d5aeb843540c7a33c8987cff02778:
      image_group_id: I1KG14440
      title: ''
      volume_number: 116
      total_pages: 218
    17254b91fe994b3bb11c763b7d39fd61:
      image_group_id: I1KG14441
      title: ''
      volume_number: 117
      total_pages: 230
    1882361de617485c978f30ef77720cf7:
      image_group_id: I1KG14442
      title: ''
      volume_number: 118
      total_pages: 218
    b4e455307c714e2cadf1475190b491a8:
      image_group_id: I1KG14443
      title: ''
      volume_number: 119
      total_pages: 0
    c79aa85c731c44b2b74c9f8a6fb1b2fa:
      image_group_id: I1KG14444
      title: ''
      volume_number: 120
      total_pages: 0
    1b16459ec16b4a7cb64c36728d9c1f87:
      image_group_id: I1KG14445
      title: ''
      volume_number: 121
      total_pages: 0
    34ee7246ce2b4188ac93d7c275c9e739:
      image_group_id: I1KG14446
      title: ''
      volume_number: 122
      total_pages: 0
    6303ef346df842e881020a60ce2326f9:
      image_group_id: I1KG14447
      title: ''
      volume_number: 123
      total_pages: 0
    5f7d6af42e3043398060cf6d76c00fa1:
      image_group_id: I1KG14448
      title: ''
      volume_number: 124
      total_pages: 0
    31fb3ed95bcb453ea5eab338e87c602b:
      image_group_id: I1KG14449
      title: ''
      volume_number: 125
      total_pages: 0
    5f9320fe688a43b5b9d7f94ccff19d1d:
      image_group_id: I1KG14450
      title: ''
      volume_number: 126
      total_pages: 0
    822c2aa0985641d1a0ad7ac251be9c44:
      image_group_id: I1KG14451
      title: ''
      volume_number: 127
      total_pages: 0
    8b286e257e9f408184878c6cf38acb75:
      image_group_id: I1KG18803
      title: ''
      volume_number: 128
      total_pages: 0
    920b8b581a9d41fd8e24e5d0e772453a:
      image_group_id: I1KG18804
      title: ''
      volume_number: 129
      total_pages: 0
    14dca938a44b4247b143304e44d18b07:
      image_group_id: I1KG18805
      title: ''
      volume_number: 130
      total_pages: 0
    a7c18968939a43af989897f4b00f9600:
      image_group_id: I1KG18806
      title: ''
      volume_number: 131
      total_pages: 0
    9b50bf77c2cf4d85a97f725a7d42f2e6:
      image_group_id: I1KG18807
      title: ''
      volume_number: 132
      total_pages: 0
    d0ccdfebe0824cd7b8b921b081c3f26d:
      image_group_id: I1KG18808
      title: ''
      volume_number: 133
      total_pages: 0
    a92fc10caa934f02898b033f80fadf65:
      image_group_id: I1KG18809
      title: ''
      volume_number: 134
      total_pages: 0
    c5b28508fd0247648072afd298635bb7:
      image_group_id: I1KG18810
      title: ''
      volume_number: 135
      total_pages: 0
    d003c35542644362a3c6217cde7ebdee:
      image_group_id: I1KG18811
      title: ''
      volume_number: 136
      total_pages: 216
    0ea1c8c67d52427cadccdf2c7cca8a67:
      image_group_id: I1KG18812
      title: ''
      volume_number: 137
      total_pages: 0
    504c013eee0e46da978d8016951672c1:
      image_group_id: I1KG18813
      title: ''
      volume_number: 138
      total_pages: 216
    5f8d2bf9bfd4449ebc2e4e526d4010c1:
      image_group_id: I1KG18814
      title: ''
      volume_number: 139
      total_pages: 216
    e9634ba790b54dbba47d2cb3e1254619:
      image_group_id: I1KG18815
      title: ''
      volume_number: 140
      total_pages: 0
    56dbcbb91ead42f4829b99b1c00b53ad:
      image_group_id: I1KG18816
      title: ''
      volume_number: 141
      total_pages: 218
    3c88c74411e54e1782aacafa4ab4b4d9:
      image_group_id: I1KG18817
      title: ''
      volume_number: 142
      total_pages: 0
    f6d8a86f710f4a399358f0b7881e293c:
      image_group_id: I1KG18818
      title: ''
      volume_number: 143
      total_pages: 218
    0372d1cbc4c04df6929b298ebdd50420:
      image_group_id: I2DB56796
      title: ''
      volume_number: 1
      total_pages: 76
    3e52a049ccd94730ac6fad6e8eaa6c4f:
      image_group_id: I2DB56797
      title: ''
      volume_number: 2
      total_pages: 78
    a07388c29eda45aba607e5c0d11b361d:
      image_group_id: I2DB56798
      title: ''
      volume_number: 3
      total_pages: 92
    96f27c35b2684ff8a47a897fbe8db223:
      image_group_id: I2DB56799
      title: ''
      volume_number: 4
      total_pages: 90
    d5a3c12ee8aa467d887550a45758727c:
      image_group_id: I2DB56800
      title: ''
      volume_number: 5
      total_pages: 74
    9c93b8be1047453394eeaf0e9788e286:
      image_group_id: I2DB56801
      title: ''
      volume_number: 6
      total_pages: 86
    0ac797da8d05420797578bff0e3c7b81:
      image_group_id: I2DB56802
      title: ''
      volume_number: 7
      total_pages: 90
    b818a76bff074e28946efe2807ae66f6:
      image_group_id: I2DB56803
      title: ''
      volume_number: 8
      total_pages: 90
    3699d612537d4784a4ce904d34abad93:
      image_group_id: I2DB56804
      title: ''
      volume_number: 9
      total_pages: 86
    759650e7238645ddbaa0645a671f2bfc:
      image_group_id: I2DB56805
      title: ''
      volume_number: 10
      total_pages: 86
    ce3d2d010b914d0280f2d6669bc89bdf:
      image_group_id: I2DB56806
      title: ''
      volume_number: 11
      total_pages: 102
    aefca374e498413985e965f2e30f7140:
      image_group_id: I2DB56807
      title: ''
      volume_number: 12
      total_pages: 102
    f839b8baee4145b0837ab4fe5a611176:
      image_group_id: I2DB56808
      title: ''
      volume_number: 13
      total_pages: 126
    720e965bcd594575818de62bc57818c4:
      image_group_id: I2DB56809
      title: ''
      volume_number: 14
      total_pages: 102
    db1e61c8e86a4380a3408500ff97bdc6:
      image_group_id: I2DB56810
      title: ''
      volume_number: 15
      total_pages: 10
    52de2911d6e3459492d4d2ba1b3cad54:
      image_group_id: I2DB56811
      title: ''
      volume_number: 16
      total_pages: 102
    845ecb9bf1a943aca1120c0cbc329d7a:
      image_group_id: I2DB56812
      title: ''
      volume_number: 17
      total_pages: 0
    d19b9f31dbfb45dc895824f744378330:
      image_group_id: I2DB56813
      title: ''
      volume_number: 18
      total_pages: 102
    d216663d1b0a4ef6bc32eb73ec8bb26f:
      image_group_id: I2DB56814
      title: ''
      volume_number: 19
      total_pages: 54
    1565fbc7b7874374815b05daafbec33c:
      image_group_id: I2DB56815
      title: ''
      volume_number: 20
      total_pages: 0
    8cfdfd323de243c3a6de3f351fc13b55:
      image_group_id: I2DB56816
      title: ''
      volume_number: 21
      total_pages: 102
    9df60635bc284ac5a6e6effd337bd45d:
      image_group_id: I2DB56817
      title: ''
      volume_number: 22
      total_pages: 130
    8dcc8afc1e594ea187962f32e610ef98:
      image_group_id: I2DB56818
      title: ''
      volume_number: 23
      total_pages: 118
    301ef54621694ef1a0ff1d58421d7aa6:
      image_group_id: I2DB56819
      title: ''
      volume_number: 24
      total_pages: 118
    29512fc1322f473482f72c126fd26be3:
      image_group_id: I2DB56820
      title: ''
      volume_number: 25
      total_pages: 126
    c4f7a479f9c744629b579e53c973a347:
      image_group_id: I2DB56821
      title: ''
      volume_number: 26
      total_pages: 0
    6af1547061b344e492dde06f87b21400:
      image_group_id: I2DB56822
      title: ''
      volume_number: 27
      total_pages: 172
    599d3e48b1834151a51299f345656d45:
      image_group_id: I2DB56823
      title: ''
      volume_number: 28
      total_pages: 98
    1c75d258f43b42aa9b9e717876168813:
      image_group_id: I2DB56824
      title: ''
      volume_number: 29
      total_pages: 106
    5bd591051bb04b0c93c3e03d17d8a311:
      image_group_id: I2DB56825
      title: ''
      volume_number: 30
      total_pages: 78
    d966f1a241794b01a31b624c0ff9db3e:
      image_group_id: I2DB56826
      title: ''
      volume_number: 31
      total_pages: 82
    e5f9f321084049b7883421f76de800d9:
      image_group_id: I2DB56827
      title: ''
      volume_number: 32
      total_pages: 86
    2fde10c901ee42ad9e62d761b602ed51:
      image_group_id: I2DB56828
      title: ''
      volume_number: 33
      total_pages: 86
    2c9b482b1ea9472f96d003780c0850cd:
      image_group_id: I2DB56829
      title: ''
      volume_number: 34
      total_pages: 86
    dc92e7c8d3e942d8b53a6ecf4c4ece77:
      image_group_id: I2DB56830
      title: ''
      volume_number: 35
      total_pages: 90
    ee977466c30e44889fe4c650289a4363:
      image_group_id: I2DB56831
      title: ''
      volume_number: 36
      total_pages: 94
    b5e099f773b141bc9e3a3ef434954adc:
      image_group_id: I2DB56832
      title: ''
      volume_number: 37
      total_pages: 86
    4a4ad781b8364ca7846bd321d4c8c277:
      image_group_id: I2DB56833
      title: ''
      volume_number: 38
      total_pages: 86
    1972351358dc42988fcb3eb6b272ca48:
      image_group_id: I2DB56834
      title: ''
      volume_number: 39
      total_pages: 88
    66172ec8f9bb4710b48a89e885c80c94:
      image_group_id: I2DB56835
      title: ''
      volume_number: 40
      total_pages: 152
    5774b11392a24144a8c9052cb585a41c:
      image_group_id: I2DB56836
      title: ''
      volume_number: 41
      total_pages: 122
    9263e6dc81874432b5ec9e88ef577b6e:
      image_group_id: I2DB56837
      title: ''
      volume_number: 42
      total_pages: 98
    83868420c42a4d2c91124953c18dfcf7:
      image_group_id: I2DB56838
      title: ''
      volume_number: 43
      total_pages: 118
    51016132e9474065aa864e31e4e03c31:
      image_group_id: I2DB56839
      title: ''
      volume_number: 44
      total_pages: 90
    1fecdddca075460498dc100a32d96d17:
      image_group_id: I2DB56840
      title: ''
      volume_number: 45
      total_pages: 90
    bddd5bab1b35430bb3b8a1c1236d3d27:
      image_group_id: I2DB56841
      title: ''
      volume_number: 46
      total_pages: 94
    7aecd7223dbb451d9234d548e72eca49:
      image_group_id: I2DB56842
      title: ''
      volume_number: 47
      total_pages: 90
    635496f27a5a46d19779afd196465bc8:
      image_group_id: I2DB56843
      title: ''
      volume_number: 48
      total_pages: 90
    28b2f8859939482682fe6d11f09bf89a:
      image_group_id: I2DB56844
      title: ''
      volume_number: 49
      total_pages: 86
    93e33ac47cf041e6ad175e5a7aedc609:
      image_group_id: I2DB56845
      title: ''
      volume_number: 50
      total_pages: 86
    c2c5c99b3a5f497d8e862bd84991f68e:
      image_group_id: I2DB56846
      title: ''
      volume_number: 51
      total_pages: 138
    0166aed9417d4132b0e66ff230a6c2ea:
      image_group_id: I2DB56847
      title: ''
      volume_number: 52
      total_pages: 86
    ba94500c3e864f24a21e97f0fb7add3b:
      image_group_id: I2DB56848
      title: ''
      volume_number: 53
      total_pages: 86
    3d515069f6d748f79aabfd26fbc1a0e7:
      image_group_id: I2DB56849
      title: ''
      volume_number: 54
      total_pages: 86
    882695fd2e3642b5a3a1f00a26cd24d8:
      image_group_id: I2DB56850
      title: ''
      volume_number: 55
      total_pages: 86
    489272213e0047229692a4e8fe732e08:
      image_group_id: I2DB56851
      title: ''
      volume_number: 56
      total_pages: 126
    305b36363533432684f523d3190d0bb1:
      image_group_id: I2DB56852
      title: ''
      volume_number: 57
      total_pages: 126
    fc617abad59f411ba1ec1a849590f1e0:
      image_group_id: I2DB56853
      title: ''
      volume_number: 58
      total_pages: 126
    020b9812d8004679a32718709ea5ca1c:
      image_group_id: I2DB56854
      title: ''
      volume_number: 59
      total_pages: 126
    5fc7f3a7d7264694a32c38141a8157d0:
      image_group_id: I2DB56855
      title: ''
      volume_number: 60
      total_pages: 134
    d4ff0682c4084ee0ac8a4387dc6223e9:
      image_group_id: I2DB56856
      title: ''
      volume_number: 61
      total_pages: 134
    c1923c3181f640d193c8bc9664bfc8ef:
      image_group_id: I2DB56857
      title: ''
      volume_number: 62
      total_pages: 134
    d7735eba8c1c4d47b1def60ec70aaad7:
      image_group_id: I2DB56858
      title: ''
      volume_number: 63
      total_pages: 132
    3fdcda916547463ba8b5e7fdd4c103c1:
      image_group_id: I2DB56859
      title: ''
      volume_number: 64
      total_pages: 126
    2ea0ce81e90541e4b69459727a1626ca:
      image_group_id: I2DB56860
      title: ''
      volume_number: 65
      total_pages: 126
    726dbe563f2343608a960df88e7d7c29:
      image_group_id: I2DB56861
      title: ''
      volume_number: 66
      total_pages: 126
    02ee4f5f7408415797ddd14d6b09ff0c:
      image_group_id: I2DB56862
      title: ''
      volume_number: 67
      total_pages: 126
    d42a989785b14349bf70c76480aa65a1:
      image_group_id: I2DB56863
      title: ''
      volume_number: 68
      total_pages: 126
    3355bce555a94f3d9d1c4822443ebbd0:
      image_group_id: I2DB56864
      title: ''
      volume_number: 69
      total_pages: 126
    2a580d4132714fb398223d3b8af9509b:
      image_group_id: I2DB56865
      title: ''
      volume_number: 70
      total_pages: 126
    47798dd1c9ba495cad6283a584cbc277:
      image_group_id: I2DB56866
      title: ''
      volume_number: 71
      total_pages: 126
    882be509bb634fdcb47495a37219e2a6:
      image_group_id: I2DB56867
      title: ''
      volume_number: 72
      total_pages: 176
    18af0a5ecb454ed681f6a79626c86d57:
      image_group_id: I2DB56868
      title: ''
      volume_number: 73
      total_pages: 176
    488dc91fbf734d8a844f2f8b16b9bd85:
      image_group_id: I2DB56869
      title: ''
      volume_number: 74
      total_pages: 182
    3de03d8afec9440da8a0eb7dfc9c07ec:
      image_group_id: I2DB56870
      title: ''
      volume_number: 75
      total_pages: 186
    318452d975a44ec7ba0ef8a78084029f:
      image_group_id: I2DB56871
      title: ''
      volume_number: 76
      total_pages: 168
    7d62913571ee4278ab419242fdd67061:
      image_group_id: I2DB56872
      title: ''
      volume_number: 77
      total_pages: 166
    4ce88ca8d2554f39b024e1d8746aa353:
      image_group_id: I2DB56873
      title: ''
      volume_number: 78
      total_pages: 166
    ea0036c660034ffca05d2a57a4818ef6:
      image_group_id: I2DB56874
      title: ''
      volume_number: 79
      total_pages: 166
    2b4c0fe643c84b858011495d8ec4cbf1:
      image_group_id: I2DB56875
      title: ''
      volume_number: 80
      total_pages: 166
    10565a41c2d045eb970135abe8be7cc2:
      image_group_id: I2DB56876
      title: ''
      volume_number: 81
      total_pages: 166
    8adc63a5f10d458aa065f75c0295f172:
      image_group_id: I2DB56877
      title: ''
      volume_number: 82
      total_pages: 166
    edc1fec953964daeb91f141c4a7d363e:
      image_group_id: I2DB56878
      title: ''
      volume_number: 83
      total_pages: 214
    6bacd9dedc8c4f528d996a2776e7ee91:
      image_group_id: I2DB56879
      title: ''
      volume_number: 84
      total_pages: 166
    ef7f7617c0ec4bda87c5c2e3bf97c104:
      image_group_id: I2DB56880
      title: ''
      volume_number: 85
      total_pages: 166
    edd23722fb3e4d72be81aa3747fe0d0a:
      image_group_id: I2DB56881
      title: ''
      volume_number: 86
      total_pages: 166
    ca9f340db22a475c8c592ea21401e065:
      image_group_id: I2DB56882
      title: ''
      volume_number: 87
      total_pages: 166
    4e1edf0ddf684d4fa5bc942f89663257:
      image_group_id: I2DB56883
      title: ''
      volume_number: 88
      total_pages: 170
    076ac46a1a8848b9806bec34712d5f8c:
      image_group_id: I2DB56884
      title: ''
      volume_number: 89
      total_pages: 172
    75ab7020fb0c41b08670e44971d7e0e8:
      image_group_id: I2DB56885
      title: ''
      volume_number: 90
      total_pages: 170
    191365718bf446bb833a98312b03bc76:
      image_group_id: I2DB56886
      title: ''
      volume_number: 91
      total_pages: 172
    8a2dfd32a2ec4895bc407462265203e1:
      image_group_id: I2DB56887
      title: ''
      volume_number: 92
      total_pages: 170
    2cb84e027d8c49ee9ae00af75285ee37:
      image_group_id: I2DB56888
      title: ''
      volume_number: 93
      total_pages: 172
    78d30e4d4ac6495382e08b0b79fbdebf:
      image_group_id: I2DB56889
      title: ''
      volume_number: 94
      total_pages: 0
    8af398af83f146f398f48339390f6683:
      image_group_id: I2DB56890
      title: ''
      volume_number: 95
      total_pages: 170
    8255dad78cd648748daf16dcf9e16e78:
      image_group_id: I2DB56891
      title: ''
      volume_number: 96
      total_pages: 170
    becd1c00175e49958df3e8deb9592c3c:
      image_group_id: I2DB56892
      title: ''
      volume_number: 97
      total_pages: 172
    7ed180a33a44491abbe70be0c7424f69:
      image_group_id: I2DB56893
      title: ''
      volume_number: 98
      total_pages: 170
    81e047f0282c4a3592f42efaf9e7f837:
      image_group_id: I2DB56894
      title: ''
      volume_number: 99
      total_pages: 170
    aeb9ee5d4833451f9abec6fa0147924e:
      image_group_id: I2DB56895
      title: ''
      volume_number: 100
      total_pages: 218
    1f153fea9a4d401083813e8865e3644d:
      image_group_id: I2DB56896
      title: ''
      volume_number: 101
      total_pages: 220
    dd6df4b221bf4b2bb0830f7ca23f10aa:
      image_group_id: I2DB56897
      title: ''
      volume_number: 102
      total_pages: 220
    b0d5bcfb6bf9401188341c6e212d6ae8:
      image_group_id: I2DB56898
      title: ''
      volume_number: 103
      total_pages: 218
    ab39d634f1df4f60b502c30993155001:
      image_group_id: I2DB56899
      title: ''
      volume_number: 104
      total_pages: 218
    75e3449545da4fbcad8394c986ee8a47:
      image_group_id: I2DB56900
      title: ''
      volume_number: 105
      total_pages: 218
    07e7c618705746c1a68506ee6409e5f0:
      image_group_id: I2DB56901
      title: ''
      volume_number: 106
      total_pages: 218
    254ec3e20846473aa510c106ff3fb31a:
      image_group_id: I2DB56902
      title: ''
      volume_number: 107
      total_pages: 218
    19794f207f884079a8a28e8eb30ffa9b:
      image_group_id: I2DB56903
      title: ''
      volume_number: 108
      total_pages: 218
    0cb89bdcd6dc45e394c90b962d9a6dcb:
      image_group_id: I2DB56904
      title: ''
      volume_number: 109
      total_pages: 218
    8d2c8292025b4ae183a41a177c0745a4:
      image_group_id: I2DB56905
      title: ''
      volume_number: 110
      total_pages: 218
    5f183eda10c4428b85eecf070e86cbea:
      image_group_id: I2DB56906
      title: ''
      volume_number: 111
      total_pages: 218
